---
- name: Get list of private SSH keys to deploy from DEPLOY_PRIVATE_SSH_KEYS
  set_fact:
    ssh_keys: "{{ (lookup('env', 'DEPLOY_PRIVATE_SSH_KEYS') | default('')).split(',') | map('trim') | list }}"
  when: lookup('env', 'DEPLOY_PRIVATE_SSH_KEYS') | default('') | trim != ''
  no_log: true

- name: Deploy private SSH keys
  copy:
    content: "{{ lookup('env', item) }}"
    dest: "/home/{{ lookup('env', 'DOCKFLOW_USER') }}/.ssh/{{ item }}"
    owner: "{{ lookup('env', 'DOCKFLOW_USER') }}"
    group: "{{ lookup('env', 'DOCKFLOW_USER') }}"
    mode: '0600'
  loop: "{{ ssh_keys | default([]) }}"
  when: ssh_keys is defined
  no_log: true

- name: Add private SSH keys to ssh-agent
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add /home/{{ lookup('env', 'DOCKFLOW_USER') }}/.ssh/{{ item }}
  loop: "{{ ssh_keys | default([]) }}"
  when: ssh_keys is defined
  no_log: true
