---
- name: Set lock file path
  set_fact:
    lock_file: "{{ lock_dir }}/{{ stack_name }}.lock"

- name: Release deploy lock
  file:
    path: "{{ lock_file }}"
    state: absent

- name: Display lock released
  debug:
    msg: "Deploy lock released for {{ stack_name }}"
