services:
  web:
    image: test-web-app
    build:
      context: ../..
      dockerfile: Dockerfile.web
    ports:
      - "${WEB_PORT}:80"
    deploy:
      replicas: 2
      placement:
        constraints: []
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure