services:
  web:
    image: test-remote-web-app
    build:
      context: ../..
      dockerfile: Dockerfile.web
    ports:
      - "${WEB_PORT}:80"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
