---
- name: Configure host machine
  hosts: all:!localhost
  become: yes
  vars_files:
    - roles/portainer/vars/vault.yml

  roles:
    - role: geerlingguy.docker
      when: not (skip_docker_install | default(false) | bool)
    - role: nginx
      tags:
        - nginx
    - role: portainer
