all:
  hosts:
    REMOTE_HOST:
      ansible_host: "{{ lookup('env', 'HOST') }}"
      ansible_user: "{{ lookup('env', 'USER') }}"
      ansible_port: "{{ lookup('env', 'PORT') | default(22) }}"
      ansible_ssh_private_key_file: ssh/remote_private_key