stages:
  - build
  - deploy-build
  - deploy

include:
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.4/.gitlab/workflows/build.yml'
  - remote: 'https://raw.githubusercontent.com/Shawiizz/devops/refs/tags/1.0.4/.gitlab/workflows/deploy.yml'
