stages:
  # Build stage for continuous integration
  - build

  # Deploy your application on tag or branch push
  - deploy

include:
  # Continuous Integration (CI) template for building Docker images (not used for deployment)
  - remote: 'https://raw.githubusercontent.com/Shawiizz/dockflow/refs/tags/1.0.54/.gitlab/workflows/build.yml'

  # Deploy your application on tag push
  - remote: 'https://raw.githubusercontent.com/Shawiizz/dockflow/refs/tags/1.0.54/.gitlab/workflows/deploy.yml'

  # Deploy your application on branch push (will deploy to production environment)
  - remote: 'https://raw.githubusercontent.com/Shawiizz/dockflow/refs/tags/1.0.54/.gitlab/workflows/deploy-branch.yml'