---
- name: Create scripts directory in user home if it doesn't exist
  ansible.builtin.file:
    path: "/home/{{ dockflow_user }}/scripts"
    state: directory
    owner: "{{ dockflow_user }}"
    group: "{{ dockflow_user }}"
    mode: '0755'

- name: List script templates (*.sh.j2 only) 
  find:
    paths: "{{ root_path }}/.deployment/templates/scripts"
    patterns: "*.sh.j2"
    recurse: false
  register: script_templates
  delegate_to: localhost

- name: Copy script templates to user home
  template:
    src: "{{ item.path }}"
    dest: "/home/{{ dockflow_user }}/scripts/{{ item.path | basename | regex_replace('\\.sh\\.j2$', '.sh') }}"
    owner: "{{ dockflow_user }}"
    group: "{{ dockflow_user }}"
    mode: '0755'
  loop: "{{ script_templates.files }}"
  when: script_templates.matched > 0
  register: scripts_copy

- name: Execute all scripts in user home
  ansible.builtin.command: "bash /home/{{ dockflow_user }}/scripts/{{ item.path | basename | regex_replace('\\.sh\\.j2$', '.sh') }}"
  loop: "{{ script_templates.files }}"
  when: script_templates.matched > 0
  register: scripts_execution
