name: Build

on:
  workflow_call:
    inputs:
      free-disk-space:
        required: false
        type: boolean
        default: false
        description: "Free disk space by removing unnecessary tools"

env:
  DOCKFLOW_REPOSITORY_URL: https://github.com/Shawiizz/dockflow.git
  DOCKFLOW_FRAMEWORK_VERSION: 1.0.44

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker images

    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ inputs.free-disk-space }}
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install docker-decompose
        run: npm i -g shawiizz-decomposerize

      - name: Clone dockflow repository
        run: git clone --branch "$DOCKFLOW_FRAMEWORK_VERSION" "$DOCKFLOW_REPOSITORY_URL" dockflow

      - name: Build Docker images
        run: |
          # Prepare secrets file for load_env.sh
          echo '${{ toJSON(secrets) }}' > secrets.json

          export ENV="build"
          export VERSION="build"

          # Load environment variables using helper script (will also load secrets)
          source dockflow/.github/scripts/load_env.sh "$ENV"
          
          # Export vars and render all docker files
          bash dockflow/.github/scripts/export_to_ansible_vars_and_render.sh
          
          bash dockflow/.github/scripts/build_docker_images.sh
